final List<Map<String, dynamic>> allEvents = [
  {
    "title": "Music Concert",
    "genre": "Music",
    "location": "Surat",
    "dateTime": "25 Sep, 2025 10:00 AM",
    "poster": "https://picsum.photos/400/200",
    "detailPoster": "https://picsum.photos/400/600",
    "gallery": [
      "https://picsum.photos/150/150",
      "https://picsum.photos/151/150",
      "https://picsum.photos/152/150",
    ],
    "about": "This is a music concert happening in Surat. Enjoy live performances!",
    "price": 500,
    "type": "upcoming",
  },
  {
    "title": "Comedy Night",
    "genre": "Comedy",
    "location": "City Hall",
    "dateTime": "26 Sep, 2025 7:00 PM",
    "poster": "https://picsum.photos/400/200",
    "detailPoster": "https://picsum.photos/400/600",
    "gallery": [
      "https://picsum.photos/153/150",
      "https://picsum.photos/154/150",
      "https://picsum.photos/155/150",
    ],
    "about": "Stand-up comedy night with top comedians performing live.",
    "price": 400,
    "type": "popular",
  },
  {
    "title": "Art Exhibition",
    "genre": "Art",
    "location": "City Center",
    "dateTime": "27 Sep, 2025 5:00 PM",
    "poster": "https://picsum.photos/400/200",
    "detailPoster": "https://picsum.photos/400/600",
    "gallery": [
      "https://picsum.photos/156/150",
      "https://picsum.photos/157/150",
      "https://picsum.photos/158/150",
    ],
    "about": "Explore beautiful art from local artists.",
    "price": 200,
    "type": "recommendation",
  },
  {
    "title": "Music Concert",
    "genre": "Music",
    "location": "Surat",
    "dateTime": "25 Sep, 2025 10:00 AM",
    "poster": "https://picsum.photos/400/200?1",
    "detailPoster": "https://picsum.photos/400/600?1",
    "gallery": [
      "https://picsum.photos/150/150?1",
      "https://picsum.photos/151/150?1",
    ],
    "about": "This is a music concert happening in Surat. Enjoy live performances!",
    "price": 500,
    "type": "upcoming",
  },
  {
    "title": "Comedy Night",
    "genre": "Comedy",
    "location": "City Hall",
    "dateTime": "26 Sep, 2025 7:00 PM",
    "poster": "https://picsum.photos/400/200?2",
    "detailPoster": "https://picsum.photos/400/600?2",
    "gallery": [
      "https://picsum.photos/153/150?2",
      "https://picsum.photos/154/150?2",
    ],
    "about": "Stand-up comedy night with top comedians performing live.",
    "price": 400,
    "type": "popular",
  },
  {
    "title": "Art Exhibition",
    "genre": "Art",
    "location": "City Center",
    "dateTime": "27 Sep, 2025 5:00 PM",
    "poster": "https://picsum.photos/400/200?3",
    "detailPoster": "https://picsum.photos/400/600?3",
    "gallery": [
      "https://picsum.photos/156/150?3",
      "https://picsum.photos/157/150?3",
    ],
    "about": "Explore beautiful art from local artists.",
    "price": 200,
    "type": "recommendation",
  },
  {
    "title": "Food Festival",
    "genre": "Food",
    "location": "Town Square",
    "dateTime": "28 Sep, 2025 12:00 PM",
    "poster": "https://picsum.photos/400/200?4",
    "detailPoster": "https://picsum.photos/400/600?4",
    "gallery": [
      "https://picsum.photos/158/150?4",
      "https://picsum.photos/159/150?4",
    ],
    "about": "Taste dishes from local and international chefs.",
    "price": 300,
    "type": "upcoming",
  },
  {
    "title": "Tech Conference",
    "genre": "Tech",
    "location": "Innovation Park",
    "dateTime": "29 Sep, 2025 9:00 AM",
    "poster": "https://picsum.photos/400/200?5",
    "detailPoster": "https://picsum.photos/400/600?5",
    "gallery": [
      "https://picsum.photos/160/150?5",
      "https://picsum.photos/161/150?5",
    ],
    "about": "Join industry experts for talks and workshops.",
    "price": 600,
    "type": "popular",
  },
  {
    "title": "Dance Show",
    "genre": "Dance",
    "location": "Apple Hub",
    "dateTime": "30 Sep, 2025 6:00 PM",
    "poster": "https://picsum.photos/400/200?6",
    "detailPoster": "https://picsum.photos/400/600?6",
    "gallery": [
      "https://picsum.photos/162/150?6",
      "https://picsum.photos/163/150?6",
    ],
    "about": "Watch a spectacular dance performance.",
    "price": 450,
    "type": "recommendation",
  },
  {
    "title": "Movie Premiere",
    "genre": "Entertainment",
    "location": "Grand Cinema",
    "dateTime": "01 Oct, 2025 8:00 PM",
    "poster": "https://picsum.photos/400/200?7",
    "detailPoster": "https://picsum.photos/400/600?7",
    "gallery": [
      "https://picsum.photos/164/150?7",
      "https://picsum.photos/165/150?7",
    ],
    "about": "Premiere of a blockbuster movie with red carpet.",
    "price": 700,
    "type": "upcoming",
  },
  {
    "title": "Book Fair",
    "genre": "Literature",
    "location": "Library Center",
    "dateTime": "02 Oct, 2025 10:00 AM",
    "poster": "https://picsum.photos/400/200?8",
    "detailPoster": "https://picsum.photos/400/600?8",
    "gallery": [
      "https://picsum.photos/166/150?8",
      "https://picsum.photos/167/150?8",
    ],
    "about": "Explore books and meet authors in person.",
    "price": 100,
    "type": "popular",
  },
  {
    "title": "Photography Workshop",
    "genre": "Photography",
    "location": "Studio X",
    "dateTime": "03 Oct, 2025 2:00 PM",
    "poster": "https://picsum.photos/400/200?9",
    "detailPoster": "https://picsum.photos/400/600?9",
    "gallery": [
      "https://picsum.photos/168/150?9",
      "https://picsum.photos/169/150?9",
    ],
    "about": "Learn photography techniques from professionals.",
    "price": 350,
    "type": "recommendation",
  },
  {
    "title": "Jazz Night",
    "genre": "Music",
    "location": "Blue Lounge",
    "dateTime": "04 Oct, 2025 7:00 PM",
    "poster": "https://picsum.photos/400/200?10",
    "detailPoster": "https://picsum.photos/400/600?10",
    "gallery": [
      "https://picsum.photos/170/150?10",
      "https://picsum.photos/171/150?10",
    ],
    "about": "Enjoy live jazz music in a cozy atmosphere.",
    "price": 400,
    "type": "upcoming",
  },
  {
    "title": "Marathon",
    "genre": "Sports",
    "location": "City Streets",
    "dateTime": "05 Oct, 2025 6:00 AM",
    "poster": "https://picsum.photos/400/200?11",
    "detailPoster": "https://picsum.photos/400/600?11",
    "gallery": [
      "https://picsum.photos/172/150?11",
      "https://picsum.photos/173/150?11",
    ],
    "about": "Participate in the annual city marathon.",
    "price": 200,
    "type": "popular",
  },
  {
    "title": "Yoga Retreat",
    "genre": "Health",
    "location": "Green Hills",
    "dateTime": "06 Oct, 2025 7:00 AM",
    "poster": "https://picsum.photos/400/200?12",
    "detailPoster": "https://picsum.photos/400/600?12",
    "gallery": [
      "https://picsum.photos/174/150?12",
      "https://picsum.photos/175/150?12",
    ],
    "about": "Relax and rejuvenate with expert yoga instructors.",
    "price": 500,
    "type": "recommendation",
  },

  // You can continue adding until you reach 20+ total events
];

/// Filters for different lists
final List<Map<String, dynamic>> upcomingEvents = allEvents.where((e) => e["type"] == "upcoming").toList();

final List<Map<String, dynamic>> popularEvents = allEvents.where((e) => e["type"] == "popular").toList();

final List<Map<String, dynamic>> recommendedEvents = allEvents.where((e) => e["type"] == "recommendation").toList();
